### ISSUE TITLE
please update install directions

### ISSUE THREAD

**Issue by rofoto** [limzykenneth/p5.wasm#26]
Hello, 
 I am building the master branch ( since the release has not been updated in almost 2 years ) and after successfully building it does not produce the p5.wasm.js ,index.bundle.js and  p5.wasm files. It instead produces 

- p5_wasm.js
- p5_wasm_bg.js
- p5_wasm_bg.wasm

along with some typescript files ( which I assume I do not need to include as I am self hosting the lib in my projects ) 

if this is the current correct set of files, the install directions should reflect that, It would also be helpful; if possible, to provide an updated release so that people can avoid the extra pain of having to set up rust in order to build out the project.

**Comment by limzykenneth** [comment]
I haven't tried to build this project in quite awhile now and possibly some of the defaults used by the build tools have changed. I'll try to look into it if I have the time but I don't expect to be putting out a new release as all the commits after 0.3.1 are build dependencies updates and not feature updates, so a new release will not be different from 0.3.1. You can continue to use 0.3.1 without issue.

**Comment by limzykenneth** [comment]
Build should be fixed now, please comment below if still not working.
