### ISSUE TITLE
p5.js seems to have been imported multiple times. Please remove the duplicate import

### ISSUE THREAD

**Issue by joex92** [limzykenneth/p5.wasm#4]
when using it like this:
```js
// This is to stop global mode from starting automatically
p5.instance = true;

// Write your p5 sketch as usual
function setup(){
	//...
}

function draw(){
	//...
}

// Wait for promise to resolve then start p5 sketch
window.p5WasmReady.then(() => {
	new p5();
});
```
I get this in the console, is it ok?
```console
p5.js seems to have been imported multiple times. Please remove the duplicate import
```

**Comment by limzykenneth** [comment]
It is ok, the check present in p5.js itself didn't anticipate it being used like this (ie. explicit call of `new p5()`) so it warns here but everything should work the same as usual.

**Comment by joex92** [comment]
I'm actually doing this in the html file:
```html
    <script language="javascript" type="text/javascript" src="node_modules/p5/lib/p5.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/p5.wasm@0.2.0/dist/p5.wasm.js"></script>
    <script>
        var wasmready = false;
        // This is to stop global mode from starting automatically
        p5.instance = true;
    </script>
    <script src="p5script.js"></script>
    <script>
        // Wait for promise to resolve then start p5 sketch
        window.p5WasmReady.then(() => {
            new p5();
            wasmready = true;
        });
    </script>
```
added this to the `.htaccess`:
```php
    AddType application/wasm .wasm
    AddOutputFilterByType DEFLATE application/wasm
```

I have to create a variable to know if wasm is loaded, because I had issues when adding wasm methods in the p5 script, telling me that the wasm state wasn't ready, so I had to do something like this with the variable I created:
```js 
if (wasmready){
    d = wasm.dist(0,0,wasm.random(),wasm.random());
} else {
    d = dist(0,0,random(),random());
}
```
so this means that I have to basically have 2 scripts just in case wasm isn't loaded...

**Comment by limzykenneth** [comment]
Is this block of code
```javascript
if (wasmready){
    d = wasm.dist(0,0,wasm.random(),wasm.random());
} else {
    d = dist(0,0,random(),random());
}
```
inside `setup` or `draw`?

If so can you share a more complete sketch code?

**Comment by joex92** [comment]
> Is this block of code
> 
> ```js
> if (wasmready){
>     d = wasm.dist(0,0,wasm.random(),wasm.random());
> } else {
>     d = dist(0,0,random(),random());
> }
> ```
> 
> inside `setup` or `draw`?
> 
> If so can you share a more complete sketch code?

that was an example but it's inside `draw`, I'm using this function to update pixel alpha values to "illuminate" an image (the image's pixels are loaded in setup):
```js
function imgLight(img,radius = 10){
    for (let i = 0; i < img.pixels.length/4; i++){
        img.pixels[(i*4)+3] = 0;
    }
    const x_ = [
        (mouseX - radius*2).clip(0,img.width-1), 
        (mouseX + radius*2).clip(0,img.width-1)
        ];
    const y_ = [
        (mouseY - radius*2).clip(0,img.height-1), 
        (mouseY + radius*2).clip(0,img.height-1)
        ];
    for (let x = x_[0]; x < x_[1]; x++) {
        for (let y = y_[0]; y < y_[1]; y++) {
            // Calculate the 1D location from a 2D grid
            let loc = ((x + y * img.width) * 4);
            let a, d = 0;
            a = img.pixels[loc];
            // Calculate an amount to change brightness based on proximity to the mouse
            let maxdist = radius;
            if (wasmready){
                d = wasm.dist(x, y, mouseX, mouseY);
            } else {
                d = dist(x, y, mouseX, mouseY);
            }
            let adjustbrightness = (255 * (maxdist - d)) / maxdist;
            a += adjustbrightness;
            if (wasmready){
                a = wasm.constrain(a, 0, 255);
            } else {
                a = constrain(a, 0, 255);
            }
            let pixloc = (y * width + x) * 4;
            img.pixels[(pixloc + 3)] = a;
        }
    }
    img.updatePixels();
}
```
Doing this, it makes it work perfectly... I can make the radius bigger than 30 and the FPS won't drop... 
(I'm doing more stuff over the image)


I created a clip method for Numbers because I wasn't using p5 before, so I still use it:
```js
  Number.prototype.clip = function (mn=-1,mx=1) {
    if(arguments.length==1||arguments.length==2){
      if (arguments.length==1){
        mn = -Infinity;
        mx = arguments[0];
      } else{
        mn = arguments[0];
        mx = arguments[1];
      }
    }
    return min(mx, max(this.valueOf(), mn));
  };
```

**Comment by limzykenneth** [comment]
In your code `wasm.random()` isn't implemented in p5.wasm yet, you can use `random()` directly. If after that you are still having problem, can you try console logging `wasm` in `setup()` (put `console.log(wasm)` in the setup function) and see what the output is.

**Comment by limzykenneth** [comment]
Does [this example](https://editor.p5js.org/limzykenneth/sketches/fkaZ13ZCZ) works for you?

**Comment by joex92** [comment]
> In your code `wasm.random()` isn't implemented in p5.wasm yet, you can use `random()` directly. If after that you are still having problem, can you try console logging `wasm` in `setup()` (put `console.log(wasm)` in the setup function) and see what the output is.

oh sorry, I haven't checked if random was implemented, sorry... that was my bad... I was just trying to show how I was using it... 
ok, this is what I got without changing anything that I already had:
![image](https://user-images.githubusercontent.com/645579/101378380-04f47b80-3881-11eb-8290-9125df27b2a5.png)

**Comment by joex92** [comment]
> Does [this example](https://editor.p5js.org/limzykenneth/sketches/fkaZ13ZCZ) works for you?

yes... but I had the issues when using in `draw()`...

**Comment by joex92** [comment]
ok, this is weird... I'm going to comment out my `if` statement and leave only the wasm method... I'm guessing I know what was the issue...

**Comment by limzykenneth** [comment]
> yes... but I had the issues when using in draw()...

Moving the relevant lines to `draw()` in the example should work as well, can you try it?

From your screenshot of console.log p5.wasm should be correctly loaded otherwise it would say `undefined`, can you post the actual error message you are having?

**Comment by joex92** [comment]
> > yes... but I had the issues when using in draw()...
> 
> Moving the relevant lines to `draw()` in the example should work as well, can you try it?
> 
> From your screenshot of console.log p5.wasm should be correctly loaded otherwise it would say `undefined`, can you post the actual error message you are having?

well... i believe the issue was that when I got the error I was still trying to understand why it had to be like this:
```html
    <script language="javascript" type="text/javascript" src="node_modules/p5/lib/p5.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/p5.wasm@0.2.0/dist/p5.wasm.js"></script>
    <script>
        var wasmready = false;
        // This is to stop global mode from starting automatically
        p5.instance = true;
    </script>
    <script src="p5script.js"></script>
    <script>
        // Wait for promise to resolve then start p5 sketch
        window.p5WasmReady.then(() => {
            new p5();
            wasmready = true;
        });
    </script>
```
I have more script files as helpers, although only the main script is using the wasm methods...
maybe it was my bad when I was doing it like this:
```html
    <script language="javascript" type="text/javascript" src="node_modules/p5/lib/p5.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/p5.wasm@0.2.0/dist/p5.wasm.js"></script>
    <script>
        // This is to stop global mode from starting automatically
        p5.instance = true;
        // Wait for promise to resolve then start p5 sketch
        window.p5WasmReady.then(() => {
            new p5();
        });
    </script>
    <script src="p5script.js"></script>
```
because I remember doing that kind of thing... well I guess in the end it was my bad...

**Comment by joex92** [comment]
is it possible to not use `wasm.dist()` and make the already `dist()` go through wasm?

**Comment by limzykenneth** [comment]
The script loading and execution order probably have something to do with what you are seeing here but if it is working for you now then that's great. There are some improvements to be made especially in terms of global mode, I'll just need time to do it....

> is it possible to not use wasm.dist() and make the already dist() go through wasm?

If you are sure you don't need the default `dist` and don't mind p5.js complaining at you again, you can do something like this:

```javascript
window.p5WasmReady.then(() => {
  new p5();
  dist = wasm.dist;
});
```
and it should replace the default `dist` with `wasm.dist`.

**Comment by joex92** [comment]
> The script loading and execution order probably have something to do with what you are seeing here but if it is working for you now then that's great. There are some improvements to be made especially in terms of global mode, I'll just need time to do it....

oh ok, I hope you get time to improve it and add more p5 methods...

> 
> > is it possible to not use wasm.dist() and make the already dist() go through wasm?
> 
> If you are sure you don't need the default `dist` and don't mind p5.js complaining at you again, you can do something like this:
> 
> ```js
> window.p5WasmReady.then(() => {
>   new p5();
>   dist = wasm.dist;
> });
> ```
> 
> and it should replace the default `dist` with `wasm.dist`.

so could I do a loop there to replace every single method you got ported to wasm to replace the default p5 one?

**Comment by limzykenneth** [comment]
If you want to yes, but do note that p5.wasm does not always have the same function signatures as the original functions of p5.js so you may want to be more selective about it. Do checkout API.md to see what correspond to what.

**Comment by joex92** [comment]
> If you want to yes, but do note that p5.wasm does not always have the same function signatures as the original functions of p5.js so you may want to be more selective about it. Do checkout API.md to see what correspond to what.

oh ok... what do you mean by "same function signatures"? I'll check out the API.md... thanks...

anyways, in the end it was something I did wrong so now I don't need the `wasmready` variable I was using anymore... I'll close the issue for now... thanks 👍

**Comment by joex92** [comment]
> If you want to yes, but do note that p5.wasm does not always have the same function signatures as the original functions of p5.js so you may want to be more selective about it. Do checkout API.md to see what correspond to what.

Oh I see... many of the methods don't have the same variable name... and you separated 2d from 3d methods... I get it now... well, I'll be selective for each project then... thanks...
